### PR TITLE
 changed polling to accept multiple urls

### PR DESCRIPTION
**Pull request by chrisbolin**
reviving #24 for you, @maamounapprise. 

now that we have CI set up, you can see the failures. Once you fix those we can merge!

### CODE REVIEW

**Comment by maamounapprise** [comment]
@chrisbolin great will fix it this weekend!

**Comment by chrisbolin** [comment]
@maamounapprise could we talk about the use case for this? I just want to make sure it's necessary, as it will probably increase the bundle size.

**Comment by chrisbolin** [comment]
and to be clear, I don't mean to suggestion that you don't have a real problem you need to solve! I just want us to think thru all available solutions :)

**Comment by maamounapprise** [comment]
@chrisbolin which one is increasing the bundle size

**Comment by chrisbolin** [comment]
I think my main concern is just added complexity that I have to maintain :) That's why I want to make sure I understand the *why* really well.

But the size of the package will increase if we had async/await as well.

**Comment by maamounapprise** [comment]
@chrisbolin I am not sure which module you are referring, is it babel polyfill? Because I tried removing it then it errored out in jest and the alternative was babel runtime which 3x bigger than babel polyfill :O, so I guess I would have to shift to .then instead of await but then I read several articles mentioning that await is better that .then in error handling.  

In babel polyfill documentation they did mention something about the size: 

> Size
The polyfill is provided as a convenience but you should use it with @babel/preset-env and the useBuiltIns option so that it doesn't include the whole polyfill which isn't always needed. Otherwise, we would recommend you import the individual polyfills manually.

**Comment by chrisbolin** [comment]
yeah, the babel polyfill adds to the size of the package. and of course any new code adds to the size of the package. it also increases the complexity of the project, the cost to maintain it, and the barriers to change it in the future.

all of those reasons are why **I really want to understand the problem we are trying to solve.** when does this issue come up? is there a better way to address it? is it widespread or a corner case?

let's answer those first, and then worry about the implementation details.

**Comment by maamounapprise** [comment]
@chrisbolin cool, check your email :)

**Comment by chrisbolin** [comment]
cleaning up PRs and issues. if you'd like to reopen this, go for it :D

**Pull request closed without merging**
